ALTER TABLE JOUEUR
    ADD CONSTRAINT CHK_JOUEUR_EMAIL
        CHECK (email_joueur LIKE '%@%.%');


ALTER TABLE JOUEUR
    ADD CONSTRAINT CHK_JOUEUR_DATE_INSCRIPTION
        CHECK (date_inscription <= CURDATE());


ALTER TABLE HISTORIQUE_CONNEXION
    ADD CONSTRAINT CHK_HIST_IP
        CHECK (
            adresse_ip REGEXP '^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}$'
            OR LENGTH(adresse_ip) <= 45
        );


ALTER TABLE HISTORIQUE_CONNEXION
    ADD CONSTRAINT CHK_HIST_DATE
        CHECK (date_connexion <= NOW());

ALTER TABLE EDITION
    ADD CONSTRAINT CHK_EDITION_PRIX
        CHECK (prix_edition >= 0);


ALTER TABLE TOURNOI
    ADD CONSTRAINT CHK_TOURNOI_DATES
        CHECK (date_debut_tr < date_fin_tr);

ALTER TABLE TOURNOI
    ADD CONSTRAINT CHK_TOURNOI_TYPE
        CHECK (type_tournoi IN ('Ouvert', 'Sur invitation'));

ALTER TABLE TOURNOI
    ADD CONSTRAINT CHK_TOURNOI_STATUT
        CHECK (statut_tournoi IN ('Ouvert', 'Fermé', 'Terminé'));

ALTER TABLE TOURNOI
    ADD CONSTRAINT CHK_TOURNOI_MAX_EQUIPES
        CHECK (nb_max_equipes >= 2);

ALTER TABLE TOURNOI
    ADD CONSTRAINT CHK_TOURNOI_CASHPRIZE
        CHECK (cashprize_total >= 0);


ALTER TABLE RECOMPENSE
    ADD CONSTRAINT CHK_RECOMP_CLASSEMENT
        CHECK (classement IN (1, 2, 3));

ALTER TABLE RECOMPENSE
    ADD CONSTRAINT CHK_RECOMP_MONTANT
        CHECK (montant >= 0);

ALTER TABLE AFFRONTEMENT
    ADD CONSTRAINT CHK_MATCH_EQUIPES_DIFFERENTES
        CHECK (id_equipe1 <> id_equipe2);

ALTER TABLE AFFRONTEMENT
    ADD CONSTRAINT CHK_MATCH_SCORE_EQ1
        CHECK (score_eq1 >= 0);

ALTER TABLE AFFRONTEMENT
    ADD CONSTRAINT CHK_MATCH_SCORE_EQ2
        CHECK (score_eq2 >= 0);

ALTER TABLE AFFRONTEMENT
    ADD CONSTRAINT CHK_MATCH_DUREE
        CHECK (duree_match >= 1);


ALTER TABLE STATISTIQUE_JOUEUR
    ADD CONSTRAINT CHK_STAT_KILLS
        CHECK (kills >= 0);

ALTER TABLE STATISTIQUE_JOUEUR
    ADD CONSTRAINT CHK_STAT_DEATHS
        CHECK (deaths >= 0);

ALTER TABLE STATISTIQUE_JOUEUR
    ADD CONSTRAINT CHK_STAT_ASSISTS
        CHECK (assists >= 0);

ALTER TABLE STATISTIQUE_JOUEUR
    ADD CONSTRAINT CHK_STAT_SCORE
        CHECK (score_individuel >= 0);
